// Generated by local/build_pages.mjs 2026-09-14T17:53:22.610Z
window.REISEVALG_CONFIG = { apiBase: "https://reisevalg-kix.loca.lt/api", vapidPublicKey: "BHqebHY3ubW2pxu5OhDDYZMn3qMyA-4zl-3OkDZT_vAxw5mv2lEjug6PBKLardntEsrIFINY8pEwvOm17mmviqs", testMode: false, environment: "pages", apiDiscoveryUrl: "https://raw.githubusercontent.com/ElNaRex/reisevalg/main/api.json" };
